language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "16"
git:
  depth: 3
script:
  - yarn run build
  - yarn run export
deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep_histoyry: true
  github-token: $GITHUB_TOKEN
  local_dir: out
  target_branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: main
